#!/bin/bash

echo 'Starting build'
#mvn clean install

echo 'Removing ROOT folder'
#rm -rf /usr/local/tomcat/webapps/ROOT

echo 'Copying to tomcat directory'
#cp target/*.war /usr/local/tomcat/webapps/ROOT.war

echo 'Starting tomcat'
cd /usr/local/tomcat/bin

sh startup.sh

tail -f /usr/local/tomcat/logs/catalina.out
